import 'package:json_annotation/json_annotation.dart';

/// Collaboration role held by a member of a shopping list.
///
/// The wire values are mirrored by `firestore.rules`; renaming one requires a
/// rules change and a data migration.
@JsonEnum(valueField: 'wire')
enum MemberRole {
  owner('owner', 3),
  editor('editor', 2),
  viewer('viewer', 1),
  guest('guest', 0);

  const MemberRole(this.wire, this.rank);

  final String wire;

  /// Higher rank implies strictly more capability.
  final int rank;

  static MemberRole fromWire(String? value) {
    for (final role in MemberRole.values) {
      if (role.wire == value) {
        return role;
      }
    }
    return MemberRole.guest;
  }

  bool get isOwner => this == MemberRole.owner;

  /// Owners and editors may mutate list content.
  bool get canEditItems => rank >= MemberRole.editor.rank;

  /// Owners, editors and viewers may tick items off.
  bool get canCompleteItems => rank >= MemberRole.viewer.rank;

  /// Only owners may delete or transfer a list.
  bool get canDeleteList => isOwner;

  bool get canManageMembers => isOwner;

  /// Guests observe the conversation without contributing.
  bool get canSendMessages => rank >= MemberRole.viewer.rank;

  bool get canInvite => rank >= MemberRole.editor.rank;

  bool atLeast(MemberRole other) => rank >= other.rank;
}

/// Relative urgency of a shopping item.
@JsonEnum(valueField: 'wire')
enum ItemPriority {
  low('low', 0),
  normal('normal', 1),
  high('high', 2),
  urgent('urgent', 3);

  const ItemPriority(this.wire, this.weight);

  final String wire;
  final int weight;

  static ItemPriority fromWire(String? value) {
    for (final priority in ItemPriority.values) {
      if (priority.wire == value) {
        return priority;
      }
    }
    return ItemPriority.normal;
  }
}

/// Unit of measure attached to an item quantity.
@JsonEnum(valueField: 'wire')
enum MeasurementUnit {
  piece('piece'),
  gram('g'),
  kilogram('kg'),
  milliliter('ml'),
  liter('l'),
  pack('pack'),
  box('box'),
  bottle('bottle'),
  can('can'),
  bag('bag'),
  bunch('bunch'),
  dozen('dozen'),
  ounce('oz'),
  pound('lb'),
  fluidOunce('fl_oz'),
  gallon('gal');

  const MeasurementUnit(this.wire);

  final String wire;

  static MeasurementUnit fromWire(String? value) {
    for (final unit in MeasurementUnit.values) {
      if (unit.wire == value) {
        return unit;
      }
    }
    return MeasurementUnit.piece;
  }

  bool get isMetric => const {
    MeasurementUnit.gram,
    MeasurementUnit.kilogram,
    MeasurementUnit.milliliter,
    MeasurementUnit.liter,
  }.contains(this);

  bool get isImperial => const {
    MeasurementUnit.ounce,
    MeasurementUnit.pound,
    MeasurementUnit.fluidOunce,
    MeasurementUnit.gallon,
  }.contains(this);
}

/// Preferred measurement system, used to pick default units.
@JsonEnum(valueField: 'wire')
enum MeasurementSystem {
  metric('metric'),
  imperial('imperial');

  const MeasurementSystem(this.wire);

  final String wire;

  static MeasurementSystem fromWire(String? value) =>
      value == imperial.wire ? imperial : metric;
}

/// Kind of payload carried by a chat message.
@JsonEnum(valueField: 'wire')
enum MessageType {
  text('text'),
  image('image'),
  voice('voice'),

  /// Generated by the backend to narrate list events inside the conversation.
  system('system');

  const MessageType(this.wire);

  final String wire;

  static MessageType fromWire(String? value) {
    for (final type in MessageType.values) {
      if (type.wire == value) {
        return type;
      }
    }
    return MessageType.text;
  }

  bool get hasAttachment => this == image || this == voice;
}

/// Category of an in-app or push notification.
@JsonEnum(valueField: 'wire')
enum NotificationType {
  invitationReceived('invitation_received'),
  invitationAccepted('invitation_accepted'),
  itemAdded('item_added'),
  itemDeleted('item_deleted'),
  itemCompleted('item_completed'),
  listCompleted('list_completed'),
  listShared('list_shared'),
  memberJoined('member_joined'),
  memberLeft('member_left'),
  messageReceived('message_received'),
  mention('mention'),
  reminder('reminder'),
  system('system');

  const NotificationType(this.wire);

  final String wire;

  static NotificationType fromWire(String? value) {
    for (final type in NotificationType.values) {
      if (type.wire == value) {
        return type;
      }
    }
    return NotificationType.system;
  }
}

/// Audit-trail verbs written to `activity_logs`.
@JsonEnum(valueField: 'wire')
enum ActivityAction {
  listCreated('list_created'),
  listUpdated('list_updated'),
  listArchived('list_archived'),
  listUnarchived('list_unarchived'),
  listDeleted('list_deleted'),
  listDuplicated('list_duplicated'),
  listCompleted('list_completed'),
  itemAdded('item_added'),
  itemUpdated('item_updated'),
  itemCompleted('item_completed'),
  itemUncompleted('item_uncompleted'),
  itemDeleted('item_deleted'),
  itemReordered('item_reordered'),
  memberInvited('member_invited'),
  memberJoined('member_joined'),
  memberRemoved('member_removed'),
  memberLeft('member_left'),
  memberRoleChanged('member_role_changed'),
  messageSent('message_sent'),
  aiGenerated('ai_generated');

  const ActivityAction(this.wire);

  final String wire;

  static ActivityAction fromWire(String? value) {
    for (final action in ActivityAction.values) {
      if (action.wire == value) {
        return action;
      }
    }
    return ActivityAction.listUpdated;
  }
}

/// Lifecycle of an invitation.
@JsonEnum(valueField: 'wire')
enum InvitationStatus {
  pending('pending'),
  accepted('accepted'),
  declined('declined'),
  revoked('revoked'),
  expired('expired');

  const InvitationStatus(this.wire);

  final String wire;

  static InvitationStatus fromWire(String? value) {
    for (final status in InvitationStatus.values) {
      if (status.wire == value) {
        return status;
      }
    }
    return InvitationStatus.pending;
  }

  bool get isActionable => this == pending;
}

/// Symbologies recognised by the scanner.
@JsonEnum(valueField: 'wire')
enum BarcodeSymbology {
  ean13('ean13'),
  ean8('ean8'),
  upcA('upc_a'),
  upcE('upc_e'),
  qr('qr'),
  isbn('isbn'),
  code128('code128'),
  code39('code39'),
  itf('itf'),
  dataMatrix('data_matrix'),
  unknown('unknown');

  const BarcodeSymbology(this.wire);

  final String wire;

  static BarcodeSymbology fromWire(String? value) {
    for (final format in BarcodeSymbology.values) {
      if (format.wire == value) {
        return format;
      }
    }
    return BarcodeSymbology.unknown;
  }

  /// A 13-digit EAN beginning with 978/979 is a Bookland ISBN.
  bool get isProductCode =>
      const {ean13, ean8, upcA, upcE, isbn}.contains(this);
}

/// Outcome of a voice capture that is being turned into items.
@JsonEnum(valueField: 'wire')
enum VoiceCommandStatus {
  listening('listening'),
  transcribed('transcribed'),
  parsed('parsed'),
  applied('applied'),
  failed('failed');

  const VoiceCommandStatus(this.wire);

  final String wire;

  static VoiceCommandStatus fromWire(String? value) {
    for (final status in VoiceCommandStatus.values) {
      if (status.wire == value) {
        return status;
      }
    }
    return VoiceCommandStatus.failed;
  }
}

/// Aggregation window for statistics documents.
@JsonEnum(valueField: 'wire')
enum StatisticsPeriod {
  daily('daily'),
  weekly('weekly'),
  monthly('monthly'),
  yearly('yearly'),
  allTime('all_time');

  const StatisticsPeriod(this.wire);

  final String wire;

  static StatisticsPeriod fromWire(String? value) {
    for (final period in StatisticsPeriod.values) {
      if (period.wire == value) {
        return period;
      }
    }
    return StatisticsPeriod.monthly;
  }
}

/// What a favourite entry points at.
@JsonEnum(valueField: 'wire')
enum FavoriteTargetType {
  list('list'),
  item('item'),
  template('template');

  const FavoriteTargetType(this.wire);

  final String wire;

  static FavoriteTargetType fromWire(String? value) {
    for (final type in FavoriteTargetType.values) {
      if (type.wire == value) {
        return type;
      }
    }
    return FavoriteTargetType.list;
  }
}

/// Device platform recorded alongside an FCM token.
@JsonEnum(valueField: 'wire')
enum DevicePlatform {
  android('android'),
  ios('ios'),
  web('web'),
  other('other');

  const DevicePlatform(this.wire);

  final String wire;

  static DevicePlatform fromWire(String? value) {
    for (final platform in DevicePlatform.values) {
      if (platform.wire == value) {
        return platform;
      }
    }
    return DevicePlatform.other;
  }
}

/// Triage severity of a bug report.
@JsonEnum(valueField: 'wire')
enum BugSeverity {
  low('low'),
  medium('medium'),
  high('high'),
  critical('critical');

  const BugSeverity(this.wire);

  final String wire;

  static BugSeverity fromWire(String? value) {
    for (final severity in BugSeverity.values) {
      if (severity.wire == value) {
        return severity;
      }
    }
    return BugSeverity.medium;
  }
}

/// Workflow state shared by feedback and bug reports.
@JsonEnum(valueField: 'wire')
enum ReportStatus {
  open('open'),
  triaged('triaged'),
  inProgress('in_progress'),
  resolved('resolved'),
  closed('closed');

  const ReportStatus(this.wire);

  final String wire;

  static ReportStatus fromWire(String? value) {
    for (final status in ReportStatus.values) {
      if (status.wire == value) {
        return status;
      }
    }
    return ReportStatus.open;
  }
}

/// How a shopping list is sorted in the UI.
@JsonEnum(valueField: 'wire')
enum ListSortOption {
  recentlyUpdated('recently_updated'),
  createdNewest('created_newest'),
  createdOldest('created_oldest'),
  alphabetical('alphabetical'),
  completion('completion'),
  memberCount('member_count');

  const ListSortOption(this.wire);

  final String wire;

  static ListSortOption fromWire(String? value) {
    for (final option in ListSortOption.values) {
      if (option.wire == value) {
        return option;
      }
    }
    return ListSortOption.recentlyUpdated;
  }
}

/// How items inside a list are ordered.
@JsonEnum(valueField: 'wire')
enum ItemSortOption {
  manual('manual'),
  alphabetical('alphabetical'),
  category('category'),
  priority('priority'),
  completion('completion'),
  recentlyAdded('recently_added');

  const ItemSortOption(this.wire);

  final String wire;

  static ItemSortOption fromWire(String? value) {
    for (final option in ItemSortOption.values) {
      if (option.wire == value) {
        return option;
      }
    }
    return ItemSortOption.manual;
  }
}

/// Filter applied to the list overview.
@JsonEnum(valueField: 'wire')
enum ListFilter {
  all('all'),
  active('active'),
  archived('archived'),
  favorites('favorites'),
  pinned('pinned'),
  ownedByMe('owned_by_me'),
  sharedWithMe('shared_with_me'),
  completed('completed');

  const ListFilter(this.wire);

  final String wire;

  static ListFilter fromWire(String? value) {
    for (final filter in ListFilter.values) {
      if (filter.wire == value) {
        return filter;
      }
    }
    return ListFilter.all;
  }
}

/// How an item entered a list, used for statistics and undo affordances.
@JsonEnum(valueField: 'wire')
enum ItemSource {
  manual('manual'),
  voice('voice'),
  barcode('barcode'),
  ai('ai'),
  template('template'),
  duplicate('duplicate');

  const ItemSource(this.wire);

  final String wire;

  static ItemSource fromWire(String? value) {
    for (final source in ItemSource.values) {
      if (source.wire == value) {
        return source;
      }
    }
    return ItemSource.manual;
  }
}

/// Sync state of a locally queued mutation.
@JsonEnum(valueField: 'wire')
enum SyncState {
  synced('synced'),
  pending('pending'),
  syncing('syncing'),
  failed('failed'),
  conflicted('conflicted');

  const SyncState(this.wire);

  final String wire;

  static SyncState fromWire(String? value) {
    for (final state in SyncState.values) {
      if (state.wire == value) {
        return state;
      }
    }
    return SyncState.synced;
  }
}

/// Operation captured by a queued offline mutation.
@JsonEnum(valueField: 'wire')
enum MutationKind {
  create('create'),
  update('update'),
  delete('delete');

  const MutationKind(this.wire);

  final String wire;

  static MutationKind fromWire(String? value) {
    for (final kind in MutationKind.values) {
      if (kind.wire == value) {
        return kind;
      }
    }
    return MutationKind.update;
  }
}

/// Themes offered in settings.
@JsonEnum(valueField: 'wire')
enum AppThemeMode {
  light('light'),
  dark('dark'),
  system('system');

  const AppThemeMode(this.wire);

  final String wire;

  static AppThemeMode fromWire(String? value) {
    for (final mode in AppThemeMode.values) {
      if (mode.wire == value) {
        return mode;
      }
    }
    return AppThemeMode.system;
  }
}

/// Templates the AI generator is able to fulfil.
@JsonEnum(valueField: 'wire')
enum AiListKind {
  weeklyShopping('weekly_shopping'),
  mealPlan('meal_plan'),
  party('party'),
  baby('baby'),
  diet('diet'),
  custom('custom');

  const AiListKind(this.wire);

  final String wire;

  static AiListKind fromWire(String? value) {
    for (final kind in AiListKind.values) {
      if (kind.wire == value) {
        return kind;
      }
    }
    return AiListKind.custom;
  }
}

/// Supported AI vendors. The active provider is resolved at runtime, so no
/// call site depends on a specific vendor.
@JsonEnum(valueField: 'wire')
enum AiProviderKind {
  openAi('openai'),
  gemini('gemini'),
  claude('claude');

  const AiProviderKind(this.wire);

  final String wire;

  static AiProviderKind fromWire(String? value) {
    for (final provider in AiProviderKind.values) {
      if (provider.wire == value) {
        return provider;
      }
    }
    return AiProviderKind.claude;
  }

  String get displayName => switch (this) {
    AiProviderKind.openAi => 'OpenAI',
    AiProviderKind.gemini => 'Gemini',
    AiProviderKind.claude => 'Claude',
  };
}

/// Role of a message in an AI conversation.
@JsonEnum(valueField: 'wire')
enum AiMessageRole {
  system('system'),
  user('user'),
  assistant('assistant');

  const AiMessageRole(this.wire);

  final String wire;

  static AiMessageRole fromWire(String? value) {
    for (final role in AiMessageRole.values) {
      if (role.wire == value) {
        return role;
      }
    }
    return AiMessageRole.user;
  }
}
